id: P8307281A
initial_creation_type: ocr
source_metadata:
  volumes:
    b0f16b6263304084af8ee91b41d067cc:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: ཚུལ་ཁྲིམས་ཀྱི་གཏམ།
      total_pages: 1144
      volume_number: 96
